spring:
  application:
    name: blogs
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.29:30306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: ydxny123
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    servlet:
      content-type: text/html
    check-template: true
    cache: false
  resources:
    static-locations: classpath:/static/,classpath:/templates/
  devtools:
    restart:
      enabled: true
debug: true
server:
  port: 8080
#mybatis-plus:
#  configuration:
#    map-underscore-to-camel-case: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
